name: 'Wheel Publisher'
description: 'Publish Source and Binary wheels for a Python project'

on:
  workflow_call:
    inputs:
      art_pattern:
        description: 'Binary artefact path from a previous job'
        type: string
        required: false
        default: 'dist-*'
      py_version:
        description: 'Version of Python to use'
        type: string
        required: false
        default: '3.x'

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/asyncproxy
    permissions:
      actions: read
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Download all wheel artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: ${{ inputs.art_pattern }}
        merge-multiple: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.py_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade build setuptools wheel

    - name: build
      run: python setup.py build sdist

    - name: Show context tree
      run: ls -lR dist

    - name: Publish package distributions to PyPI
      if: github.event_name == 'release' && github.event.action == 'created'
      uses: pypa/gh-action-pypi-publish@release/v1
