name: 'Draft Release Roller'
description: 'Publish Source and Generate Draft Release'

on:
  workflow_call:
    inputs:
      distname:
        description: 'Name (prefix) of the source tarball'
        type: string
        required: false
        default: ${{ github.event.repository.name }}
      extra_tar_args:
        description: 'Extra arguments to pass to tar when rolling the ball'
        type: string
        required: false
        default: ''
      submodules_recursive:
        description: 'Use recursive submodules'
        type: boolean
        required: false
        default: true

jobs:
  draft_and_distfile:
    name: Create Release Draft and distfile
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: ${{ inputs.submodules_recursive && 'recursive' || 'false' }}

    - name: Set Environment
      id: job_config
      run: |
        RELEASE_VER="${GITHUB_REF#refs/tags/v}"
        echo "ver=${RELEASE_VER}" >> ${GITHUB_OUTPUT}
        echo "src=${{ inputs.distname }}-${RELEASE_VER}.tar.gz" >> ${GITHUB_OUTPUT}

    - name: Create source distribution
      run: |
        set -x
        git rev-parse HEAD > revision.txt
        NAME="${{ inputs.distname }}-${{steps.job_config.outputs.ver}}"
        tar --exclude-vcs ${{ inputs.extra_tar_args }} -czvf /tmp/${{steps.job_config.outputs.src}} \
         --transform="s|^[.]|${NAME}|" .
        mv /tmp/${{steps.job_config.outputs.src}} ${{steps.job_config.outputs.src}}

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./${{steps.job_config.outputs.src}}
        draft: true
        prerelease: false
        generate_release_notes: true
